config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/mypage' => 'homes#mypage'
  get 'posts/top' => 'posts#top'
  get 'posts/favorite' => 'posts#favorite', as: 'favorite'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'

  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end
  resources :posts do
    resources :post_comments # , only: [:create, :destroy]
    resource :favorites, only: %i[create destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i[index show create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :move_to_signed_in
    # フォローする
    def create
      @user = User.find(params[:user_id])
      current_user.follow(params[:user_id])
    end
    
    # フォロー外す
    def destroy
      @user = User.find(params[:user_id])
      current_user.unfollow(params[:user_id])
    end
    
    # フォロー一覧画面
    def followings
      user = User.find(params[:user_id])
      @users = user.followings
    end
    
    # フォロワー一覧画面
    def followers
      user = User.find(params[:user_id])
      @users = user.followers
    end
    
    private
    
    def move_to_signed_in
      unless user_signed_in?
        # サインインしていないユーザーはログインページが表示される
        redirect_to '/users/sign_in'
      end
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow-btn.html.erb
<% if current_user.following?(user) %>
<i class="fas fa-users-slash"></i>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, remote: true, class: "user-follow-btn" %>
<% else %>
<i class="fas fa-user-friends"></i>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "user-follow-btn" %>
<% end %>

app/views/relationships/_follow_count.html.erb
<!--フォロー、フォロワー数の表示-->
フォロー<%= link_to @user.followings.count, user_follows_path(@user.id), class: "follow-number" %></br></br>


フォロワー<%= link_to @user.followers.count, user_followers_path(@user.id), class: "follow-number" %>

app/views/relationships/_user-follow.html.erb
<% if @users.empty? %>
<br><br><h3>　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　ユーザーはいません</h3>
<% else %>
    <%= render 'users/user_form', users: @users %>
<% end %>

app/views/relationships/create.js.erb
$("#user-follow_<%= @user.id %>").html("<%= j(render 'relationships/follow_count', user: @user) %>");
console.log("ss3")
$(".follow_<%= @user.id %>").html("<%= j(render 'relationships/follow-btn', user: @user) %>");

app/views/relationships/destroy.js.erb
$("#user-follow_<%= @user.id %>").html("<%= j(render 'relationships/follow_count', user: @user) %>");
console.log("ss3")
$(".follow_<%= @user.id %>").html("<%= j(render 'relationships/follow-btn', user: @user) %>");

app/views/relationships/followers.html.erb
<h1 class="show-user-title">
   FOLLOWER
</h1>

<%= render 'relationships/user-follow' %>

app/views/relationships/followings.html.erb
<h1 class="show-user-title">
   FOLLOW
</h1>

 <%= render 'relationships/user-follow' %>