config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/mypage' => 'homes#mypage'
  get 'posts/top' => 'posts#top'
  get 'posts/favorite' => 'posts#favorite', as: 'favorite'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'

  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end
  resources :posts do
    resources :post_comments # , only: [:create, :destroy]
    resource :favorites, only: %i[create destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i[index show create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, length: { in: 1..9 }
  validates :profile,    length: { maximum: 200 }

  # ユーザー画像
  mount_uploader :avater, AvaterUploader

  # ユーザーのアカウントが削除されると関連するものも
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :passive_of_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  # 自分がフォローする側の関係性
  has_many :relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  # 自分をフォローしている人
  has_many :followers, through: :passive_of_relationships, source: :follower
  # 自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  #フォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォロー外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか
  def following?(user)
    followings.include?(user)
  end

  enum gender: { 男性: 0, 女性: 1 }
  # 退会しているユーザーがログインできないようにする
  # def active_for_authentication?
    # super && (is_deleted == false)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_signed_in
    def show
      # ransackによる検索
      @q = Post.ransack(params[:q])
      # 検索結果を新しい順
      @q.sorts = 'updated_at desc' if @q.sorts.empty?
      @user = User.find(params[:id])
      # 新しい順にそのユーザーが投稿したものを表示
      @posts = @user.posts.order(id: 'desc')
      
      # ユーザーがすでにルームに参加しているか判断
      @currentUserEntry = Entry.where(user_id: current_user.id)
      # ユーザー詳細ページのユーザーがルームに参加しているか判断
      @userEntry = Entry.where(user_id: @user.id)
      # @userとcurrent_userが違うユーザーか確認
      if @user.id == current_user.id
      else
        # current_userが参加してる全てのルームidを出力
        @currentUserEntry.each do |cu|
          # @userが参加してる全てのルームidを出力
          @userEntry.each do |u|
            # current_userの参加してるroom_idと@userのroom_idで一致するものがあるか
            if cu.room_id == u.room_id
              @isRoom = true
              @roomId = cu.room_id
            end
          end
      end
      # isRoomがなかったら新規作成
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
      end
    end
    
    def edit
      @user = User.find(params[:id])
      if @user == current_user
      else
        redirect_to user_path(current_user.id)
      end
    end
    
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user.id)
      else
        render :edit
      end
    end
    
    def index
      # gem ransackによる検索機能
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).order(id: 'desc')
    end
    
    # 退会画面
    def unsubscribe
      @user = User.find(params[:id])
      if @user == current_user
      else
        redirect_to user_path(current_user.id)
      end
    end
    
    # 退会機能
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      reset_session
      redirect_to root_path
    end
    
    private
    
    def move_to_signed_in
      unless user_signed_in?
        # サインインしていないユーザーはログインページが表示される
        redirect_to '/users/sign_in'
      end
    end
    
    def user_params
      params.require(:user).permit(:name, :age, :gender, :profile, :bike, :is_deleted, :avater)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<% users.each do |user| %>
<!--ユーザーカード-->
<div class="index-user-card">
  <div class="index-user-box">
    <div class="index-user-avater">
     <% if user.avater? %>
        <%= image_tag user.avater.thumb.url, class: "user-avater-post" %>
     <% else %>
        <%= image_tag asset_path("default.jpg"), :size => '70x70' %>
     <% end %>
    </div>
    <!--ユーザーネーム-->
    <div class="index-user-name">
      <%= link_to user_path(user.id), class: "index-user-font" do %>
      <i class="fas fa-user"></i><%= user.name %>
    </div>
    <!--プロフィールバイク名-->
    <div class="index-user-bike">
      <i class="fas fa-motorcycle"></i><%= user.bike %>
    </div>
  </div>

</div>

<% end %>
<% end %>

app/views/users/edit.html.erb
<h1 class="show-user-title">
    PROFILE EDIT
</h1>
<!--ユーザー編集画面-->
<div class="user-edit-main">
     <div class="user-edit-card">
         <% if @user.avater? %>
             <%= image_tag @user.avater.thumb.url, class: "user-avater-useredit" %>
         <% else %>
             <%= image_tag asset_path("default.jpg"), :size => '250x250' %>
         <% end %>
     </div>
     
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
    <% end %>
      </ul>
    </div>
    
<%= form_with model:@user, local:true do |f| %>
      <div class="field01">
         <%= f.file_field :avater, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
     
      <div class="field01">
         <%= f.label :名前（必須） %><br />
         <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
      </div>
     
      <div class="field01">
         <%= f.label :年齢 %><br />
         <%= f.text_field :age, autofocus: true, autocomplete: "age" %>
      </div>

      <div class="field01">
         <%= f.label :性別 %><br />
         <%= f.label :男性 %>
         <%= f.radio_button :gender, :男性 %>
         <%= f.label :女性 %>
         <%= f.radio_button :gender, :女性 %>
      </div>

      <div class="field01">
         <%= f.label :バイク %><br />
         <%= f.text_field :bike, autofocus: true, autocomplete: "bike" %>
      </div>

      <div class="field01">
         <%= f.label :自己紹介 %><br />
         <%= f.text_area :profile, autofocus: true, autocomplete: "profile", size: "48x6" %>
      </div>
      <!--ゲストユーザーは編集できないように設定-->
      <% if current_user.name == "ゲストユーザー" %>
         <h2>編集できません</h2>
      <% else %>
         <i class="fas fa-motorcycle"></i>
         <%= f.submit 'GO!!!', class: 'post-btn' %>
         <i class="fas fa-motorcycle"></i>
</div>
<% end %>
<% end %>

app/views/users/index.html.erb
<h1 class="show-user-title">
   USERS
</h1>

<div class="user-search">
    <!----検索機能-->
    <%= search_form_for @q do |f| %>
    <%= f.label :name, "ユーザー名検索" %>
    <%= f.search_field :name_cont %>
    <%= f.label :bike, "バイク名で検索" %>
    <%= f.search_field :bike_cont %>
    <%= f.submit "検索" %>
    <% end %>
</div>


<%= render 'users/user_form', users: @users %>

app/views/users/show.html.erb
<h1 class="show-user-title">
  SHOW USER
</h1>
<!--ユーザーカード-->
<div class="user-card">
   <div class="user-image">
      <% if @user.avater? %>
      <%= image_tag @user.avater.thumb.url, class: "user-avater-usershow" %>
      <% else %>
      <%= image_tag asset_path("default.jpg"), :size => '150x150' %>
      <% end %>
    </div>

    <p class="user-name">
      名前: <%= @user.name %>
    </p>

    <p class="user-age">
      年齢: <%= @user.age %>
    </p>

    <p class="user-gender">
      性別: <%= @user.gender %>
    </p>

    <p class="user-bike">
      好きなバイク: <%= @user.bike %>
    </p>

    <div class="user-text">
      自己紹介:
       <p>
         <%= @user.profile %>
       </p>
    </div>
    <!--フォロー、フォロワー数-->
    <div id="user-follow_<%= @user.id %>" class="user-follow" >
      <%= render 'relationships/follow_count', user: @user %>
    </div>
    <!--フォロー、フォロワーボタン-->
    <% if current_user != @user %>
      <div class="follow-follower">
        <div class="follow_<%= @user.id %>">
          <%= render 'relationships/follow-btn', user: @user %>
    <% end %>
        </div>
      </div>
    　<!--チャットボタン表示-->
    <% if @user.id == current_user.id %>
    <% else %>
      <% if @isRoom == true %>
        <div class="chat-link">
          <i class="fas fa-comments"></i>
          <a href="/rooms/<%= @roomId %>">
            チャットへ
          </a>
      <% else %>
        <%= form_with model: @room, url: rooms_path, local:true do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value => @user.id %>
          <% end %>
          <div class="user-chat">
            <%= button_tag '<i class="fas fa-comment-dots"></i>チャットを始める'.html_safe, :type => "submit", class: "user-chat-start" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
       </div>


    <% if @user.id == current_user.id %>
      <p class="user-pofile-btn">
        <i class="fas fa-user-edit"></i>
        <%= link_to "プロフィール編集", edit_user_path(@user), class: "user-btn-link" %>
      </p>
      <p class="user-delete-btn">
        <i class="far fa-times-circle"></i>
        <%= link_to "退会する", unsubscribe_path(@user), class: "user-btn-link" %>
      </p>
    <% end %>
 </div>



<%= render 'posts/post_form' %>

app/views/users/unsubscribe.html.erb
<h1 class="user-draw-title">
  DISCHARGE
</h1>

<h2 class="user-draw-text">
   退会すると投稿内容はすべて削除され</br>
   アカウントを二度と戻せなくなります。
</h2>

<% if current_user.name == "ゲストユーザー" %>
   <h2>　　　　　　　　　　　　　　　　　　　　　　　　　　　　　退会できません</h2>
<% else %>
   <div class="user-draw">
     <i class="fas fa-door-open"></i>
     <%= link_to "退会する",user_path(current_user.id), method: :delete, "data-confirm" => "本当に退会しますか？" %>
   </div>
   <div class="user-undraw">
     <i class="fas fa-door-closed"></i>
     <%= link_to "退会しない", user_path(current_user) %>
   </div>
<% end %>