config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/mypage' => 'homes#mypage'
  get 'posts/top' => 'posts#top'
  get 'posts/favorite' => 'posts#favorite', as: 'favorite'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'

  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end
  resources :posts do
    resources :post_comments # , only: [:create, :destroy]
    resource :favorites, only: %i[create destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i[index show create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  # タグ付け
  acts_as_taggable
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title, { length: { in: 1..15 } }
  validates :post_profile, { length: { in: 1..200 } }
  validates :post_bike, { length: { in: 1..8 } }
  validates :image, presence: true
  
  # ユーザーがお気に入りに登録したかどうかの判定
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :move_to_signed_in
    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save
         redirect_to posts_path
      else
         render :new
      end
    end

    def index
      # gem ransackによる検索機能
      @q = Post.ransack(params[:q])
      # 検索結果の新しい順
      @q.sorts = 'updated_at desc' if @q.sorts.empty?
      # tag付け
      @posts = Post.tagged_with(params[:tag_name]).page(params[:page]) if params[:tag_name]
      if @posts == nil
        # ransackとページネーションの使用
        @posts = @q.result.includes(:user).page(params[:page])
      end
    end


    def show
      @post = Post.find(params[:id])
      @post_comment = PostComment.new
      @post_comments = @post.post_comments.order(id: 'desc').page(params[:page]).per(5)
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end

    def edit
      @post = Post.find(params[:id])
      if @post.user == current_user
      else
        redirect_to post_path(@post.id)
      end
    end

    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
         redirect_to post_path(@post.id)
      else
         render :edit
      end
    end

    def top
      # 3つまでお気に入りの多い順に記事を表示
      @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    end

    def favorite
      @favorites = Favorite.where(user_id: current_user.id)
    end

    # 投稿データのストロングパラメータ
    private

    def move_to_signed_in
      unless user_signed_in?
        # サインインしていないユーザーはログインページが表示される
        redirect_to '/users/sign_in'
      end
    end

    def post_params
      params.require(:post).permit(:title, :image, :post_profile, :post_bike, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<% post_comments.each do |post_comment| p %>

<!--コメントエリア-->
<div class="comment-card">
    <!--コメントのユーザーネーム-->
    <div class="comment-user-name">
       <%= link_to user_path(post_comment.user) do %>
           <%= post_comment.user.name %>
       <% end %>
    </div>

    <div class="comment-user-avater">
       <% if post_comment.user.avater? %>
         <%= image_tag post_comment.user.avater.thumb.url, class: "user-avater-comment" %>
       <% else %>
         <%= image_tag asset_path("default.jpg"), :size => '100x100' %>
       <% end %>
    </div>
    <!--コメントした日付-->
    <div class="comment-day">
       <%= post_comment.created_at.strftime('%Y/%m/%d') %>
    </div>
    <!--コメント削除ボタン-->
    <% if post_comment.user == current_user %>
       <div class="comment-delete">
           <i class="fas fa-backspace"></i>
           <%= link_to "コメントを削除", post_post_comment_path(post_comment.post, post_comment), remote: :true,  method: :delete %>
       </div>
    <% end %>
    <!--コメント内容-->
    <div class="comment-text">
       <%= post_comment.comment %>
    </div>

</div>

<% end %>
<!--エラーメッセージコメント-->
<% if @post_comment.errors.any? %>
   <div id="error_explanation_comment">
       <ul>
           <% @post_comment.errors.full_messages.each do |message| %>
               <li>
                   <%= message %>
               </li>
           <% end %>
           <% end %>
       </ul>
   </div>

app/views/posts/_comment_count.html.erb
コメント件数: <%= @post.post_comments.count %>

app/views/posts/_edit_post.html.erb
<%= form_with model: @post, local:true do |f| %>

    <div class="field01">
      <%= f.label :写真 %></br>
      <%= f.attachment_field :image %>
    </div>
    
    <div class="field01">
      <%= f.label :バイク名 %></br>
      <%= f.text_field :post_bike %>
    </div>
    
    <div class="field01">
      <%= f.label :タイトル %></br>
      <%= f.text_field :title, size: "40x5" %>
    </div>
    
    <div class="field01">
      <%= f.label :説明 %></br>
      <%= f.text_area :post_profile, size: "45x5" %>
    </div>
    
    <div class="field01">
      <%= f.label :タグ（半角空白で区切り） %></br>
      <%= f.text_area :tag_list, value: @post.tag_list, size: "45x2" %>
    </div>
    
    <p>
      <i class="fas fa-motorcycle"></i>
      <%= f.submit 'GO!!!', class: 'post-btn' %>
      <i class="fas fa-motorcycle"></i>
    </p>
<% end %>

app/views/posts/_error01.html.erb
<% if @post.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
  <% end %>
      </ul>
    </div>

app/views/posts/_pagenate.html.erb
<%= paginate post_comments %>

app/views/posts/_post_form.html.erb
<% @posts.each do |post| %>
   <!--投稿カード-->
   <div class="photo-card">
     <!--画像表示場所-->
     <div class="pohoto-background">
       <%= link_to post_path(post.id) do %>
         <%= attachment_image_tag post, :image, class: "image-size" %>
       <% end %>
   </div>
   <!--画像情報表示場所-->
   <div class="photo-details">
      <div class="photo-user-icon">
        <% if post.user.avater? %>
          <%= image_tag post.user.avater.thumb.url, class: "user-avater-post" %>
        <% else %>
          <%= image_tag asset_path("default.jpg"), :size => '70x70' %>
        <% end %>
      </div>
      <!--タイトル表示（13字まで）-->
      <h3 class="photo-title">
         <%= post.title.truncate(13) %>
      </h3>
      <!--ユーザーネーム-->
      <span class="photo-author">
         By<%= link_to user_path(post.user) do %>
           <%= post.user.name %>
         <% end %>
      </span>
      <!--画像の説明文(88字まで)-->
      <p class="photo-text">
        <%= post.post_profile.truncate(88) %>
      </p>
      <!--リアクション、バイク名-->
      <div class="photo-meta">
        <!--バイク名-->
        <div class="photo-bike">
          <h6>
            <%= post.post_bike %>
          </h6>
        </div>
        <!--コメント数、フォローボタン-->
        <div class="reaction">
          <h6>
            リアクション
          </h6>
          <ul>
             <li>
               <!--コメント数-->
               <%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %>
             </li>
             <li>
               <!--いいねボタン-->
               <div id="favorite_button_<%=post.id%>">
                 <%= render partial: 'favorites/favorite-btn', locals: {post: post} %>
               </div>
             </li>
         </ul>
        </div>
       </div>
     <!--タグ -->
      <div class="photo-tags">
        <h6>
          タグ
        </h6>
        <ul>
         <%= render 'posts/tag_list', tag_list: post.tag_list %>
        </ul>
      </div>

   </div>
</div>
<% end %>

app/views/posts/_search_post.html.erb
  <div class="search-form">
  <%= search_form_for @q do |f| %>
    <%= f.label :title, "タイトル" %>
    <%= f.search_field :title_cont %>
    <%= f.label :post_bike, "バイクタイトル" %>
    <%= f.search_field :post_bike_cont %>
    <%= f.submit "検索" %>
  <% end %>
 </div>

app/views/posts/_tag_list.html.erb
<% tag_list.each do |tag| %>
<%= link_to tag, posts_path(tag_name: tag) %>
<% end %>

app/views/posts/edit.html.erb
<h1 class="post-new-title">
   EDIT BIKE
</h1>

<%= render 'posts/error01' %>

<%= render 'posts/edit_post', post: @post %>

app/views/posts/favorite.html.erb
<h1 class="favorite-top">
   FAVORITE BIKE
</h1>

   <% if @favorites.present? %>
      <% @favorites.each do |favorite| %>
        <div class="photo-card">
          <div class="pohoto-background">
            <%= link_to post_path(favorite.post_id) do %>
              <%= attachment_image_tag favorite.post, :image, class: "image-size" %>
            <% end %>
          </div>

          <div class="photo-details">
            <div class="photo-user-icon">
              <% if favorite.user.avater? %>
                <%= image_tag favorite.user.avater.thumb.url, class: "user-avater-post" %>
              <% else %>
                <%= image_tag asset_path("default.jpg"), :size => '70x70' %>
              <% end %>
            </div>

            <h3 class="photo-title">
              <%= favorite.post.title.truncate(13) %>
            </h3>

            <span class="photo-author">
              By<%= link_to user_path(favorite.post.user) do %>
                <%= favorite.post.user.name %>
              <% end %>
            </span>

            <p class="photo-text">
              <%= favorite.post.post_profile.truncate(88) %>
            </p>

            <div class="photo-meta">
              <div class="photo-bike">
                <h6>
                  <%= favorite.post.post_bike.truncate(10) %>
                </h6>
              </div>

              <div class="reaction">
                <h6>
                  リアクション
                </h6>
                <ul>
                  <%= link_to "#{favorite.post.post_comments.count} コメント", post_path(favorite.post.id) %>
                </ul>
              </div>
            </div>

            <div class="photo-tags">
              <h6>
                タグ
              </h6>
              <ul>
                <%= render 'posts/tag_list', tag_list: favorite.post.tag_list %>
             </ul>
           </div>
         </div>
       </div>
     <% end %>

  <!--お気に入りがない場合-->
  <% else %>
     <h1>
       　　　　　　　　　　　　　　　　　　　　　お気に入りはありません
     </h1>
  <% end %>

app/views/posts/index.html.erb
<h1 class="index-title">
  BIKES
</h1>

<%= render 'posts/search_post' %>

 <%= render 'posts/post_form' %>

<div class="pagenate">
   <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1 class="post-new-title">
  NEW BIKE
</h1>

<%= render 'posts/error01' %>

<%= render 'posts/edit_post', post: @post %>

app/views/posts/show.html.erb
<h1 class="show-title">
   SHOW BIKE
</h1>
<!--投稿詳細画面のカード全体-->
<div class="show-main">
  <!--投稿画像-->
   <div class="show-photo">
     <%= attachment_image_tag @post, :image, class: "show-user-photo" %>
   </div>
   <!--投稿詳細画面右側-->
   <div class="show-area">
      <div class="show-area-card">
        <div class="show-user-avater">
          <% if @post.user.avater? %>
            <%= image_tag @post.user.avater.thumb.url, class: "user-avater-postshow" %>
          <% else %>
            <%= image_tag asset_path("default.jpg"), :size => '200x150' %>
          <% end %>
        </div>
        <!--タイトル-->
        <div class="show-title-photo">
          <%= @post.title %>
        </div>
        <!--バイク名-->
        <div class="show-bike">
          <i class="fas fa-motorcycle"></i>
          <%= @post.post_bike %>
        </div>
        <!--名前-->
        <div class="show-user-name">
          By<%= link_to user_path(@post.user) do %>
           <%= @post.user.name %>
          <% end %>
        </div>
        <!--説明文-->
       <div class="show-text">
         <%= @post.post_profile %>
       </div>
       <!--タグ-->
       <div class="show-tags">
         <%= render 'posts/tag_list', tag_list: @post.tag_list %>
       </div>
       <!--日付-->
       <div class="show-collection">
         <div class="show-user-day">
           <%= @post.created_at.strftime('%Y/%m/%d') %>
         </div>
         <!--いいねボタン-->
         <div class="show-favorite">
           <div id="favorite_button_<%=@post.id%>">
             <%= render partial: 'favorites/favorite-btn', locals: {post: @post} %>
            </div>
         </div>

         <% if @post.user == current_user %>
           <div class="show-edit-btn">
             <i class="fas fa-pencil-alt"></i>
             <%= link_to "編集", edit_post_path(@post) %>
           </div>

           <div class="show-delete-btn">
             <i class="fab fa-battle-net"></i>
             <%= link_to "削除", post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？" %>
           </div>
         <% end %>
       </div>
       <!--コメント件数-->
       <div class="show-comment">
         <%= render partial: 'posts/comment_count', locals: { post: @post,post_comment: @post_comment } %>
       </div>
     </div>
     <!--コメントカード-->
     <div class="post_comment">
       <%= render partial: 'posts/comment', locals: { post: @post, post_comments: @post_comments } %>
     </div>
     <!--ページネーション-->
     <div class="pagenate">
       <%= render partial: 'posts/pagenate', locals: { post_comments: @post_comments, page: @page } %>
     </div>
     <!--コメント入力画面-->
     <div class="show-comment-area">
       <%= form_with model:[@post, @post_comment], remote: :true do |f| %>
         <%= f.text_area :comment, id:"post_comment_area", row:"5", placeholder:"コメントを入力してください", size: "40x5" %>
         <p><%= f.submit "送信する", class: "comment-push-btn" %></p>
       <% end %>
     </div>
   </div>
</div>

app/views/posts/top.html.erb
<h1 class="post-top">
 BEST BIKE
</h1>
<!--検索機能を導入-->
<% @all_ranks.each do |post| %>
   <!--投稿カード-->
   <div class="photo-card">
     <!--画像場所-->
     <div class="pohoto-background">
       <%= link_to post_path(post.id) do %>
         <%= attachment_image_tag post, :image, class: "image-size" %>
       <% end %>
     </div>
     <!--画像情報表示場所-->
     <div class="photo-details">
       <div class="photo-user-icon">
         <% if post.user.avater? %>
           <%= image_tag post.user.avater.thumb.url, class: "user-avater-post" %>
         <% else %>
           <%= image_tag asset_path("default.jpg"), :size => '70x70' %>
         <% end %>
       </div>
       <!--タイトル-->
       <h3 class="photo-title">
         <%= post.title.truncate(13) %>
       </h3>
       <!--名前-->
       <span class="photo-author">
         By<%= link_to user_path(post.user) do %>
           <%= post.user.name %>
         <% end %>
         <!--説明文-->
         <p class="photo-text">
           <%= post.post_profile.truncate(88) %>
         </p>
       </span>
       <!--リアクション、バイク名-->
       <div class="photo-meta">
         <div class="photo-bike">
           <h6>
             <%= post.post_bike %>
           </h6>
         </div>

         <div class="reaction">
           <h6>
             リアクション
           </h6>
           <ul>
             <li>
               <!--コメント数-->
               <%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %>
             </li>
             <li>
               <!--いいねボタン-->
               <div id="favorite_button_<%=post.id%>">
                 <%= render partial: 'favorites/favorite-btn', locals: {post: post} %>
               </div>
             </li>
          </ul>
        </div>
     </div>
     <!--タグ付け-->
     <div class="photo-tags">
       <h6>
         タグ
       </h6>
       <ul>
         <%= render 'posts/tag_list', tag_list: post.tag_list %>
       </ul>
     </div>

    </div>
  </div>
 <% end %>