config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/mypage' => 'homes#mypage'
  get 'posts/top' => 'posts#top'
  get 'posts/favorite' => 'posts#favorite', as: 'favorite'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'

  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end
  resources :posts do
    resources :post_comments # , only: [:create, :destroy]
    resource :favorites, only: %i[create destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i[index show create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>© All rights reserved by KenInoue.Inc.</p>
 </footer>

app/views/layouts/_header.html.erb
<header>
   <div class="header">
      <h1>Bike&Like</h1>
    </div>
    
    <div id="sp-menu">
      <h2>Bike&Like</h2>
      
        <ul>
          <!--ログイン中ハンバーガーメニュー-->
          <% if user_signed_in? %>
            <li>
              <%= link_to "TOP", root_path %>
            </li>
            <li>
              <%= link_to "ABOUT", about_path %>
            </li>
            <li>
              <%= link_to "投稿一覧", posts_path %>
            </li>
            <li>
              <%= link_to '投稿フォーム', new_post_path %>
            </li>
            <li>
              <%= link_to '人気記事', posts_top_path %>
            </li>
            <li>
              <%= link_to "いいね一覧", favorite_path %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <li>
              <%= link_to 'マイページ', user_path(current_user.id) %>
            </li>
            <li>
              <%= link_to "ユーザー一覧", users_path %>
            </li>
            <li>
              <%= link_to "チャットルーム一覧", rooms_path(current_user) %>
            </li>
         <% else %>
         　　<!--ログアウトハンバーガーメニュー-->
            <li>
              <%= link_to "TOP", root_path %>
            </li>
            <li>
              <%= link_to "ABOUT", about_path %>
            </li>
            <li>
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "ログイン", new_user_session_path %>
            </li>
         <% end %>
       </ul>
   </div>
   <!--ハンバーガーアイコン-->
   <div id="hm-icon">
     <a class="menu-trigger">
        <span></span>
        <span></span>
        <span></span>
     </a>
   </div>
   
</header>

app/views/layouts/_notifications.html.erb
<!--フラッシュメッセージ-->
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert" ) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
     <title>
       Bike&Like
     </title>

      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" name="viewport"/>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <!-- コード追加　Bootstrap JavaScript読み込みコード-->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
      </script>

   </head>

   <body>
      <%= render 'layouts/header' %>
      <div class="loader-wrap">
        <div class="loader"></div>
      </div>

     <main>
       <%= render 'layouts/notifications' %>
       <%= yield %>
     </main>

       <%= render 'layouts/footer' %>
   </body>

</html>